version: "3.8"

services:
  db:
    container_name: database
    image: postgres:latest
    env_file:
      - .env
    networks:
      - dam-network
  panel:
    container_name: panel
    image: hisptanzania/dam-saas-panel:latest
    restart: always
    env_file:
      - .env
      - .env.local
    ports:
      - "3000:3000"
    networks:
      - dam-network
  core:
    container_name: core
    image: hisptanzania/dam-saas-core:latest
    env_file:
      - .env
    restart: always
    ports:
      - "3001:3001"
    networks:
      - dam-network
  messaging:
    container_name: messaging
    image: hisptanzania/dam-saas-messaging:latest
    restart: always
    env_file:
      - .env
    ports:
      - "3002:3002"
    networks:
      - dam-network
  visualizer:
    container_name: visualizer
    image: hisptanzania/dam-saas-visualizer:latest
    env_file:
      - .env

networks:
  dam-network:
    external: true
